In [9]:
import cv2 
import torch
import torch.nn.functional as f 
import matplotlib.pyplot as plt

In [5]:
image = cv2.imread("../opencv/assets/deer.png")
print(image)

[[[20 48 22]
  [20 48 22]
  [18 47 21]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[20 47 21]
  [20 48 22]
  [20 48 22]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[18 46 20]
  [19 47 21]
  [19 48 22]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 ...

 [[31 79 44]
  [31 78 45]
  [35 82 50]
  ...
  [25 65 48]
  [33 72 57]
  [39 79 64]]

 [[32 80 46]
  [33 80 47]
  [36 83 51]
  ...
  [29 69 50]
  [33 73 55]
  [41 82 64]]

 [[32 80 47]
  [33 81 49]
  [35 83 50]
  ...
  [25 65 43]
  [29 71 47]
  [30 73 49]]]


In [8]:
# it is an rgb image thats why dymention is 3
image.ndim

3

In [29]:
image = torch.tensor([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16],
    [10,7,5,6],
]).float().unsqueeze(0).unsqueeze(0) # unsqueeze mean add dymention

In [30]:
image.ndim

4

In [31]:
image

tensor([[[[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.],
          [10.,  7.,  5.,  6.]]]])

In [32]:
image.shape

torch.Size([1, 1, 5, 4])

In [33]:
# [1, 1, 5, 4] mean [batch, RGB]

In [34]:
# max pooling
pool2d = f.max_pool2d(image, kernel_size=2)
pool2d

tensor([[[[ 6.,  8.],
          [14., 16.]]]])

In [ ]:
# reduce row and col
pool2d.shape

torch.Size([1, 1, 2, 2])

In [36]:
conv = torch.nn.Conv2d(1, 1, kernel_size=2, stride=2)
output = conv(image)
output

tensor([[[[-1.6308, -2.7335],
          [-6.0416, -7.1442]]]], grad_fn=<ConvolutionBackward0>)

In [37]:
output.shape

torch.Size([1, 1, 2, 2])

In [38]:
output.ndim

4