#### Upsampling is the process of improving the resolution of an image.

##### Common upsampling Techniques
- Nearest Neighbor Interpolation → পাশের পিক্সেল কপি করে বড় করা।
- Bilinear Interpolation → চারপাশের পিক্সেলের গড় ব্যবহার করে smooth ছবি বানানো।
- Bicubic Interpolation → আরও smooth এবং realistic ছবি তৈরি করে।

In [1]:
import cv2 
import torch
import torch.nn.functional as f 
import matplotlib.pyplot as plt

In [2]:
image = torch.tensor([
    [1,2,],
    [5,6,],
]).float().unsqueeze(0).unsqueeze(0) # unsqueeze mean add dymention

In [3]:
image.shape

torch.Size([1, 1, 2, 2])

In [5]:
# Nearest_neighbour upsampling
upsample_nn = f.interpolate(image, scale_factor=2, mode="nearest")

In [6]:
upsample_nn

tensor([[[[1., 1., 2., 2.],
          [1., 1., 2., 2.],
          [5., 5., 6., 6.],
          [5., 5., 6., 6.]]]])

In [7]:
upsample_nn.shape

torch.Size([1, 1, 4, 4])

In [16]:
upsampling_b = f.interpolate(image, scale_factor=2, mode="bilinear")

In [17]:
upsampling_b

tensor([[[[1.0000, 1.2500, 1.7500, 2.0000],
          [2.0000, 2.2500, 2.7500, 3.0000],
          [4.0000, 4.2500, 4.7500, 5.0000],
          [5.0000, 5.2500, 5.7500, 6.0000]]]])

In [18]:
upsampling_b.shape

torch.Size([1, 1, 4, 4])

In [13]:
# Transposed Convolution
conv_transpose = torch.nn.ConvTranspose2d(1, 1, kernel_size=3, stride=2, padding=1)
output_transpose = conv_transpose(image)

In [14]:
output_transpose

tensor([[[[-0.5567,  0.0209, -0.8888],
          [-0.4438,  0.5163, -0.4637],
          [-1.8851,  0.9032, -2.2172]]]], grad_fn=<ConvolutionBackward0>)

In [15]:
output_transpose.shape

torch.Size([1, 1, 3, 3])