In [1]:
import torch
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [2]:
matrix = torch.tensor([[1,2,3],
                       [4,5,6]])



In [3]:
# total sum
total_sum = torch.sum(matrix)
total_sum

tensor(21)

In [4]:
# every column sum
col_sum = torch.sum(matrix, dim=0)
col_sum

tensor([5, 7, 9])

In [5]:
# every row sum
row_sum = torch.sum(matrix, dim=1)
row_sum

tensor([ 6, 15])

In [ ]:
# every row mean
row_mean = torch.mean(matrix.float(), dim=1)
row_mean

tensor([2., 5.])

In [ ]:
# max value
max_val = torch.max(matrix)
max_val

tensor(6)

In [ ]:
row_max = torch.max(matrix, dim=1)
row_max.values # আউটপুট হবে [3, 6] কারণ প্রথম সারির max=3, দ্বিতীয় সারির max=6।

tensor([3, 6])

In [14]:
row_min = torch.min(matrix, dim=1)
row_min.values # আউটপুট হবে [1, 4] কারণ প্রথম সারির max=1, দ্বিতীয় সারির max=4।

tensor([1, 4])

In [15]:
# all element Multiplication 
multiplication_all  = torch.prod(matrix)
multiplication_all

tensor(720)

In [18]:
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# row Multiplication 
multiplication_row  = torch.prod(matrix, dim=1)
multiplication_row

tensor([  6, 120])

In [19]:
# col Multiplication 
multiplication_col  = torch.prod(matrix, dim=0)
multiplication_col

tensor([ 4, 10, 18])

In [26]:
# col std 
std_col  = torch.std(matrix.float(), dim=0)
std_col

tensor([2.1213, 2.1213, 2.1213])

In [27]:
# row std 
std_row  = torch.std(matrix.float(), dim=1)
std_row

tensor([1., 1.])

### view and reshape

In [34]:
a = torch.randn(3, 4)
print(a.is_contiguous())
print(a.shape)
# transpose -> could be non- contiguous
b = a.t()
print(b.is_contiguous())
print(b.shape)

True
torch.Size([3, 4])
False
torch.Size([4, 3])


In [36]:
# view() method works in contiguous data
# it's not copy the main data

# reshape() -> work contiguous and non contiguous both
# copy the main data

In [39]:
tensor = torch.arange(12)

reshape_tensor_view = tensor.view(2, 6)
reshape_tensor_reshpae = tensor.reshape(2, 6)

print(reshape_tensor_view)
print(reshape_tensor_reshpae)

print(reshape_tensor_view.shape)
print(reshape_tensor_reshpae.shape)

print(tensor.is_contiguous())


tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
torch.Size([2, 6])
torch.Size([2, 6])
True


In [40]:
tensor3d = torch.arange(24).reshape(2, 3, 4)
tensor3d

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [41]:
flattened = tensor3d.view(-1)
flattened

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])

In [42]:
flattened.is_contiguous()

True

In [43]:
tensor2d = torch.arange(24).reshape(12, 2)
transpose = tensor2d.t()
transpose.is_contiguous()

False

In [45]:
""" 
error because this data is not contiguous
"""
tensor.view(transpose)

TypeError: view() received an invalid combination of arguments - got (Tensor), but expected one of:
 * (torch.dtype dtype)
      didn't match because some of the arguments have invalid types: (!Tensor!)
 * (tuple of ints size)
      didn't match because some of the arguments have invalid types: (!Tensor!)
