In [1]:
import torch
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [2]:
tensor_1 = torch.tensor([1,2,3])
tensor_2 = torch.tensor([4, 5, 6])

print(tensor_1.ndim)
print(tensor_1.size())

1
torch.Size([3])


In [4]:
row = torch.stack((tensor_1, tensor_2), dim=0)
print(row)

print("----------")

col = torch.stack((tensor_1, tensor_2), dim=1)
print(col)

tensor([[1, 2, 3],
        [4, 5, 6]])
----------
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [5]:
tensor_3 = torch.tensor([7, 8, 9])

In [6]:
row = torch.stack((tensor_1, tensor_2, tensor_3), dim=0)
print(row)

print("----------")

col = torch.stack((tensor_1, tensor_2, tensor_3), dim=1)
print(col)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
----------
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])
