In [1]:
import torch
import cv2
import numpy as np
import matplotlib.pyplot as plt

#### Tensor Manipulation

- reshape
- slicing
- joining or splitting
- transposing and permuting dimension

In [5]:
original_tensor = torch.arange(15)
print(original_tensor)
print(original_tensor.nelement())
print(original_tensor.ndim) 

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
15
1


In [8]:
reshape_tensor = original_tensor.reshape(3, 5)
print(reshape_tensor.nelement())
print(reshape_tensor.ndim) 
print(reshape_tensor)

15
2
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])


In [13]:
# all data calculate automatically -1
flattened_tensor = original_tensor.view(-1)
flattened_tensor
print(original_tensor.is_contiguous()) # order are same not change
print(flattened_tensor)

True
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])


### Joining Tensor

In [ ]:
tensor_01 = torch.tensor([[1,2,3], 
                          [4,5,6]])
tensor_02 = torch.tensor([[7,8,9], 
                          [10,11,12]])

concat_tensor_row = torch.cat((tensor_01, tensor_02), dim=0)
concat_tensor_col = torch.cat((tensor_01, tensor_02), dim=1)

print(tensor_01)
print(tensor_02)
print("-----")
print(concat_tensor_row)
print(concat_tensor_col)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[ 7,  8,  9],
        [10, 11, 12]])
-----
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
tensor([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]])


In [22]:
import torch

# Create a tensor with values from 0 to 11
original_tensor = torch.arange(12)

# Split into 5 chunks along dimension 0
# Since 12 is not divisible by 5, the first few chunks will have 3 elements
# and the rest will have 2 elements
chunks = torch.chunk(original_tensor, 5, dim=0)
print(chunks)

# Print each chunk
for chunk in chunks:
    print(chunk)


(tensor([0, 1, 2]), tensor([3, 4, 5]), tensor([6, 7, 8]), tensor([ 9, 10, 11]))
tensor([0, 1, 2])
tensor([3, 4, 5])
tensor([6, 7, 8])
tensor([ 9, 10, 11])


In [23]:
splits = torch.split(original_tensor, 5, dim=0)
print(splits)

# Print each chunk
for split in splits:
    print(split)

(tensor([0, 1, 2, 3, 4]), tensor([5, 6, 7, 8, 9]), tensor([10, 11]))
tensor([0, 1, 2, 3, 4])
tensor([5, 6, 7, 8, 9])
tensor([10, 11])


### Transpose
- transpose() -> swap two dimension. max and min
- permute() -> rearranges all dimension in the specified order

In [24]:
original_tensor = torch.arange(24).reshape(12, 2)

transpose_tensor = original_tensor.transpose(0, 1)


print(original_tensor)

print(original_tensor.shape)
print(transpose_tensor.shape)

print(transpose_tensor)

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]])
torch.Size([12, 2])
torch.Size([2, 12])
tensor([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22],
        [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23]])


In [27]:
""" 
change the dimension of order

1ম dimension হবে আগের 3য় dimension (index 2)

2য় dimension হবে আগের 1ম dimension (index 0)

3য় dimension হবে আগের 2য় dimension (index 1)

"""
original_tensor = torch.arange(24).reshape(2, 3, 4)



print(original_tensor)

permute_tensor = original_tensor.permute(2, 0, 1)
print(permute_tensor)


tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[[ 0,  4,  8],
         [12, 16, 20]],

        [[ 1,  5,  9],
         [13, 17, 21]],

        [[ 2,  6, 10],
         [14, 18, 22]],

        [[ 3,  7, 11],
         [15, 19, 23]]])


### Cloning and Detaching

In [28]:
import copy
a = [1,2,3]
b = copy.deepcopy(a)

print(a)
print(b)

[1, 2, 3]
[1, 2, 3]


In [ ]:
"""
requires_grad=True
PyTorch-কে বলে দিচ্ছে যে এই tensor-এর উপর যেকোনো অপারেশন ট্র্যাক করো যেন পরে gradient বের করা যায়।

"""
tensor = torch.ones(3, 3, requires_grad=True) # part of computation graph

clone_tensor = tensor.clone() # part of computation graph

print(clone_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], grad_fn=<CloneBackward0>)


In [ ]:
detached_tensor = tensor.detach() # this code will detach the tensor from the compution graph
detached_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])